Repository Hello-Kitchen/KDS-Front-End, pull requests merged in 2024-07, with the labels that each got.

#23 fix: remplacement de tout le css par tailwind du header et footer
  src/App.js
  src/components/Buttons/Buttons.css
  src/components/Buttons/Buttons.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/index.css
  tailwind.config.js
Labels: ☀️ Enhancement

#28 20 bordure gauche kds passe
  src/Components/Buttons/Buttons.js
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Components/LeftSection/LeftSection.js
  src/Components/OrdersDisplay/Orders.css
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/Pages/Dashboard/DashboardCuisine.css
  src/Pages/Dashboard/DashboardCuisine.js
  src/Pages/Dashboard/DashboardPasse.css
  src/Pages/Dashboard/DashboardPasse.js
  src/Pages/Login/Login.js
  src/Pages/Login/Logo_Hello_Kitchen.png
  src/Pages/PosRouter.js
  src/index.css
  src/index.js
  tailwind.config.js
Labels: ☀️ Enhancement

#41 fix: taille du texte de l'etat de connection reduit et hauteur du bas…
  src/Components/Footer/Footer.js
  tailwind.config.js
Labels: 🪲 Bug

#54 52 suppresion des commandes prete
  eslint.config.mjs
  src/Components/Buttons/Buttons.js
  src/Components/Footer/Footer.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/Pages/Dashboard/DashboardCuisine.js
  src/Pages/PosRouter.js
Labels: 💥 New feature
