Repository Hello-Kitchen/KDS-Front-End, pull requests merged in 2024-06, with the labels that each got.

#3 feat: Initialisation de l'application
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 👨‍🦯 Ignore for release

#9 feat: en tete modulable
  src/components/Header.css
  src/components/Header.js
  src/index.css
  src/index.js
Labels: 💥 New feature

#12 build: TailwindCSS
  package-lock.json
  package.json
  src/components/Header.css
  tailwind.config.js
Labels: 👨‍🦯 Ignore for release

#15 14 ajout url et port backend dans config kds
  .gitignore
  config/config.js
  package-lock.json
  package.json
  public/index.html
Labels: 💥 New feature

#17 4 order display component
  src/App.js
  src/components/OrdersDisplay/Orders.css
  src/components/OrdersDisplay/OrdersDisplay.js
  src/components/OrdersDisplay/SingleOrderDisplay.js
Labels: 💥 New feature

#13 feat: Ajout de la page de login avec redirection
  package-lock.json
  package.json
  src/Logo_Hello_Kitchen.png
  src/index.js
  src/pages/Login.css
  src/pages/Login.js
Labels: 💥 New feature

#19 fix: Ajout tailwindcss dans la page login
  config/config.js
  package-lock.json
  src/index.js
  src/pages/Login.css
  src/pages/Login.js
  tailwind.config.js
Labels: ☀️ Enhancement

#26 feat: ajout de l'heure dans le fichier App et envoie au Header por l'…
  src/App.js
  src/index.js
Labels: 💥 New feature
