Repository Hello-Kitchen/KDS-Front-End, pull requests merged in 2024-10, with the labels that each got.

#62 60 compliance with the new back
  README.md
  eslint.config.mjs
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/Pages/Login/Login.js
Labels: 🪲 Bug

#65 feat: handle of the JWT
  README.md
  package-lock.json
  package.json
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/Pages/Login/Login.js
Labels: 💥 New feature

#68 feat: Error modal on login screen
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/Pages/Login/Login.js
Labels: 💥 New feature

#69 docs: Add in-code (doxygen) documentation for KDS files
  src/Components/Buttons/Buttons.js
  src/Components/Footer/Footer.js
  src/Components/Header/Header.js
  src/Components/LeftSection/LeftSection.js
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/Pages/Dashboard/DashboardCuisine.js
  src/Pages/Dashboard/DashboardPasse.js
  src/Pages/Login/Login.js
  src/Pages/PosRouter.js
  src/index.js
Labels: 📚 Documentation
