Repository Hello-Kitchen/KDS-Front-End, pull requests merged in 2024-11, with the labels that each got.

#70 58 test unitairefonctionnelperformance front kds
  .babelrc
  eslint.config.mjs
  package-lock.json
  package.json
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/__tests__/Buttons.test.js
  src/__tests__/Footer.test.js
  src/__tests__/Header.test.js
  src/__tests__/OrderDisplayPasse.test.js
  src/__tests__/OrdersDisplay.test.js
  src/__tests__/SingleOrderDisplay.test.js
Labels: 💥 New feature

#85 Optimization updating food
  src/Components/OrdersDisplay/SingleOrderDisplay.js
Labels: 🪲 Bug

#87 61 optimization while updating status of a food
  src/Components/OrdersDisplay/SingleOrderDisplay.js
Labels: 🪲 Bug

#89 76 refactor buttons
  public/active-analytic.jpg
  public/active-recall.jpg
  public/active-setting.jpg
  src/Components/Buttons/Buttons.js
  src/Components/Footer/Footer.js
  src/Pages/Dashboard/DashboardCuisine.js
  src/__tests__/Buttons.test.js
  src/__tests__/Footer.test.js
  tailwind.config.js
Labels: ☀️ Enhancement

#88 Navigation button
  src/Components/Buttons/Buttons.js
  src/Components/Footer/Footer.js
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
  src/Components/OrdersDisplay/SingleOrderDisplay.js
  src/Pages/Dashboard/DashboardCuisine.js
  src/Pages/Dashboard/DashboardPasse.js
  src/__tests__/Buttons.test.js
  src/__tests__/Footer.test.js
  src/__tests__/OrdersDisplay.test.js
  src/__tests__/SingleOrderDisplay.test.js
  tailwind.config.js
Labels: 💥 New feature
