Repository Hello-Kitchen/KDS-Front-End, pull requests merged in 2025-01, with the labels that each got.

#90 80 statistics view
  src/Components/Buttons/Buttons.js
  src/Components/Footer/Footer.js
  src/Components/ModalViews/StatisticsView.js
  src/Pages/Dashboard/DashboardCuisine.js
  src/__tests__/Buttons.test.js
  src/__tests__/StatisticsView.test.js
  tailwind.config.js
Labels: 💥 New feature

#97 77 servie button implementation
  src/Components/Buttons/Buttons.js
  src/Components/Footer/Footer.js
  src/Components/OrdersDisplay/OrdersDisplay.js
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
  src/Pages/Dashboard/DashboardCuisine.js
  src/Pages/Dashboard/DashboardPasse.js
  src/__tests__/Buttons.test.js
  src/__tests__/Footer.test.js
  src/__tests__/OrderDisplayPasse.test.js
  src/__tests__/OrdersDisplay.test.js
Labels: ☀️ Enhancement

#104 fix: note duplicate when multiple ingredients modification in order
  src/Components/OrdersDisplay/SingleOrderDisplay.js
Labels: 🪲 Bug

#110 fix: change fetch to use status (ready, pending)
  src/Components/OrdersDisplay/OrdersDisplayPasse.js
Labels: 🪲 Bug
